[package]
name = "binver_derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
semver = "1.0"
proc-macro2 = "1.0"
quote = "1.0"

[dependencies.syn]
version = "1.0"
default-features = false
features = ["derive", "parsing", "printing", "extra-traits"]
